default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'postgres') %>
  host: <%= ENV.fetch("POSTGRES_HOST", 'db') %>
  username: <%= ENV.fetch("POSTGRES_USER", 'postgres') %>

development:
  <<: *default
  database: helpjuice_test_development

test:
  <<: *default
  database: helpjuice_test_test

production:
  <<: *default
  database: helpjuice_test_production
  username: helpjuice_test
  password: <%= ENV["HELPJUICE_TEST_API_DATABASE_PASSWORD"] %>
